### ISSUE TITLE
modelName in serializers/drf.js undefined

### ISSUE THREAD

**Issue by awwester** [dustinfarris/ember-django-adapter#102]
I'm getting undefined in the drf serializer inside `extractArray` for the `type.modelName variable`. I changed that to `type.typeKey` and that property is what was needed.

I'm using ember 1.13.1, ember-data 1.0.0-beta.17, and ember-django-adapter 0.5.6

**Comment by benkonrath** [comment]
ember-data-adapter 0.5.6 requires at least ember-data v1.0.0-beta.18 because there was a breaking change in beta.18. ember-data-adapter 0.5.6 should also work with ember-data v1.0.0-beta.19.2 but it won't work with ember-data >= 1.13 because of another breaking change (I'm working on a fix which I hope to finish in the next couple of days).

**Comment by benkonrath** [comment]
I forgot to mention: Please feel free to reopen this issue if you still have problems with ember-data beta.18 / beta.19. Thanks.

**Comment by awwester** [comment]
Cool, thanks! Will take a look at that.
