### ISSUE TITLE
Add "note" about jsonapi being the happy path in ember-data

### ISSUE THREAD

**Issue by holandes22** [dustinfarris/ember-django-adapter#109]
I see that the community of ember-data got behind the jsonapi spec (and with great reasons, is an amazing project), so I would like to mention this to newcomers.

If you start a project today using Django, ember and ember-data, the best way to go is to create a jsonapi compliant API in your backend. Therefore, the use of this adapter is not the best way to go in such case.
Unfortunately, as of yet, there are no good projects for Django to help write a jsonapi serializers and renderers (like there are for rails https://github.com/cerebris/jsonapi-resources).

So, sort of like a service to community and newcomers to the ember framework, I'd like to mention this somewhere in our docs.
The idea is to be very clear that is only for new projects, as legacy projects where you cannot change the API, our adapter is the way to go.

/cc @dustinfarris @benkonrath what do you guys think? it might be confusing for someone?

**Comment by dustinfarris** [comment]
I don't think we need to take an official stance on this.  If I am thinking about a new Ember project, I am not going to read an adapter's documentation to make architectural decisions.  People come to the adapter because they are already using Django REST Framework, and want to start using Ember.  I would rather not discourage them.

DRF is not the best framework for JSON API.  There are several projects that try to hack it into something like JSON API, but they are very invasive (too much so in my opinion).

While JSON API is definitely the first-class citizen of Ember Data, the use of adapters remains well documented and supported, and even encouraged by ED for those of us who either can not or simply will not adopt the new standard.

If you're thinking we should indicate, perhaps in the README, that the reason for this adapter's existence is because DRF is not JSON API compliant, I am open to that.

**Comment by benkonrath** [comment]
I have the feeling that it's still a lot of work to create JSONAPI compliant API with Django. I haven't done much research on the topic so I would feel uncomfortable recommending this path for new projects. I did a quick search and I found these projects but I have know idea how well they work though.

https://github.com/kevin-brown/drf-json-api
https://github.com/django-json-api/rest_framework_ember

As it stands now, I'm pretty happy with DRF 3 and this adapter and I plan to continue to use it - even for new projects.

**Comment by holandes22** [comment]
Yo guys do raise some very good points, but my impression still is (and this is purely speculative on my part) that the flow for a newcomer is:

1. I use django and want to start digging into ember
2. Do a google search "ember + django" and the first place they get is EDA

This is where I was coming from. But, yeah, nobody should make architectural designs purely based on our docs, so I agree no much point on mentioning this (and possibly discouraging/confusing)

@benkonrath yes, jsonapi support for DRF is very bad as of now, I'm trying to find the bandwidth to make lib for DRF similar to the rails one I mentioned. I checked the 2 libs you mentioned but unfortunately not much going on there. I'll contact their devs before starting anything of my own.

**Comment by dustinfarris** [comment]
In my opinion, for any new project, if JSON API is your first priority then DRF probably isn't the way to go.  In fact, I'm not even sure if Django is the way to go.

If I was starting a new project and wanted to jump on the JSON API bandwagon, I'd probably take a look at using Rails, or possibly one of the newer frameworks like [Phoenix](http://www.phoenixframework.org/) (which looks pretty exciting anyway).

Lucky for us DRF lovers, JSON API is supported, but not required for Ember Data.

**Comment by holandes22** [comment]
You are right, currently DRF is not really a good option for jsonapi. But it can get there, if rails did, django can too :)

Saw your addition in the README file on the jsonapi, looks great, you expressed it much better than I could :+1:  

Heard very nice things about elixir, but never heard of Phoenix, so thanks! I'll check phoenix next weekend, looks really good.
