### ISSUE TITLE
Prepare adapter to comply with upcoming version 2 of ember-data

### ISSUE THREAD

**Issue by holandes22** [dustinfarris/ember-django-adapter#110]
Basically go with the instructions laid here http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_new-serializer-api-for-custom-serializer-authors and here http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_transition-to-the-new-jsonserializer-and-restserializer-apis

And remove all the deprecation warnings of course

**Comment by benkonrath** [comment]
Since this is such a big change, perhaps we should release EDA 1.0 with the deprecation warnings and EDA 2.0 with all the deprecation warnings fixed. This allows us to make a functional release for ED 1.13 sooner and gives us some breathing room for our 2.0 release. We can always back port the 2.0 deprecation fixes to an EDA 1.1 release (or something). What do you guys think?

**Comment by holandes22** [comment]
+1

**Comment by benkonrath** [comment]
Actually I've already made the required changes (building on your PR). I'll submit my PR once your work is merged.

**Comment by holandes22** [comment]
Awesome!
