### ISSUE TITLE
Package incompatible with ember-cli-coffeescript

### ISSUE THREAD

**Issue by erichonkanen** [dustinfarris/ember-django-adapter#121]
Hello,

I am using [ember-cli-coffeescript](https://github.com/kimroen/ember-cli-coffeescript) package with my project with django api and we decided to try using this client side api adapter but ran into an issue where an error occurs on `ember server` due to coffeescript finding an `adapters/application.js` [file](https://github.com/dustinfarris/ember-django-adapter/blob/master/app/adapters/application.js) that shouldn't be there. The file in particular is actually in this package under `app/adapters/application.js`

In our app we have our own `app/adapters/application.coffee`

When I deleted `myproject/node_modules/ember-django-adapter/app/adapters/application.js`, it works again.

How can we get around this or get this package to play nice with coffeescript?

Thanks!

**Comment by benkonrath** [comment]
As far as I know this is a standard embe-cli addon so I'm not sure there's an issue with this package. Let's see what the developers of ember-cli-coffeescript have to say about this issue you filed with them.

**Comment by dustinfarris** [comment]
Yeah, that's an interesting one.  I'd say this should be addressed by ember-cli-coffeescript.  On a side note, make sure you are importing from ember-django-adapter in your own adapters/application.coffee, otherwise the adapter will not work.  See docs here: http://dustinfarris.com/ember-django-adapter/extending/

**Comment by erichonkanen** [comment]
@dustinfarris ok definitely I'm waiting to hear back on their end... We did create our own `app/adapters/application.coffee` but that was where the issue came up because it had already detected `application.js` from this package and it caused conflict

**Comment by kimroen** [comment]
Although I don't have a great solution, this issue is definitely something that stems from using ember-cli-coffeescript, not from using ember-django-adapter, so issue this can certainly be closed.

I tried to explain what is happening in the issue over there for the interested: https://github.com/kimroen/ember-cli-coffeescript/issues/87

Ideas for other solutions to explore would be appreciated!

**Comment by dustinfarris** [comment]
Hi @kimroen, thanks for the update.  Will think on this—maybe there's something we can do to get it working.

**Comment by erichonkanen** [comment]
I'll close this since it my issue has been resolved by just using javascript file instead of coffeescript file for this adapter...
