### ISSUE TITLE
store.queryRecord error

### ISSUE THREAD

**Issue by kevinwmerritt** [dustinfarris/ember-django-adapter#128]
I have something like this:

```
this.store.queryRecord('user', {email: 'myemail@gmail.com'}).then(function(user) {
  console.log(user);
});
```

The request is made successfully and I get an an array of one object back from django-rest-framework.
```
{"next":null,"previous":null,"results":[{"id":1,"email":"myemail@gmail.com","first_name":"test","last_name":"name"}]}
```
But I get this error:
```
Error: Assertion Failed: You must include an 'id' for user in an object passed to 'push'
```
Ember 1.13.5
Ember Data 1.13.7
EDA 1.0

**Comment by dustinfarris** [comment]
Thanks for reporting.  I'll look into this.

**Comment by dustinfarris** [comment]
This seems to be due to the paginated response not being handled properly.  In DS.RESTAdapter, `normalizeQueryRecordResponse` [proxies the server response](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json-serializer.js#L267-L268) to `normalizeSingleResponse`.  We handle pagination in `normalizeArrayResponse`.

I'll work on a solution.

**Comment by dustinfarris** [comment]
@kevinwmerritt just a quick update on this:  I've written a patch in #130 to handle the paginated data for queryRecord, but not 100% sure I'm going about it the right way.  I am discussing with the guys at ED—it's possible we've exposed a bug over there.

**Comment by kevinwmerritt** [comment]
@dustinfarris have you given any thought to extending the RESTserializer instead of the JSONserializer as suggested here: https://github.com/emberjs/data/issues/3331#issuecomment-129525566

**Comment by dustinfarris** [comment]
@kevinwmerritt yes, I think it's a good idea.  I'll update my PR and kick the tires a bit.

**Comment by benkonrath** [comment]
For some background, I change to extending from JSONSerializer with the update to ED 1.13 because I had problems with the RESTSerializer and I read in the ED comments that adapters should extend  the JSONSerializer. I don't remember the exact issues I had but I can dig into this a bit as well since I'm the person who changed to the JSONSerializer.

**Comment by dustinfarris** [comment]
Thanks, Ben.

**Comment by benkonrath** [comment]
PR is ready for testing in #133.
